export const RESULTS_LOADED = 'RESULTS_LOADED';
export const RESULTS_FILTERED = 'RESULTS_FILTERED';
export const CHANGE_BUDGET_FILTER = 'CHANGE_BUDGET_FILTER';
export const CHANGE_NAME_FILTER = 'CHANGE_NAME_FILTER';
export const CHANGE_STARS_FILTER = 'CHANGE_STARS_FILTER';
export const CHANGE_SORT_BY = 'CHANGE_SORT_BY';